networks:
  home:
    name: home

services:
  db:
    container_name: ${DB_NAME}  
    image: postgres:15.1-alpine
    restart: always
    env_file:
    - .env
    ports:
    - ${DB_PORT}:${DB_PORT}
    volumes:
    - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${DB_PORT}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - home

  devices:
    container_name: devices
    image: devices-app
    restart: always
    build: 
      context: ./Devices
      dockerfile: Dockerfile
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
    - home

  executor:
    container_name: executor
    image: executor-app
    restart: always
    build: 
      context: ./Executor
      dockerfile: Dockerfile
    env_file:
    - .env
    depends_on:
      devices:
        condition: service_started
    networks:
    - home

  nginx:
    container_name: smart-home-proxy
    build: ./Proxy
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./Proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - devices
    networks:
    - home

volumes:
  postgres:
    name: devices-db-data-local

