# Generated by Django 5.2.8 on 2025-12-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(choices=[('climate', 'Climate'), ('light', 'Light'), ('camera', 'Camera'), ('thermo', 'Thermo'), ('sensor', 'Sensor'), ('switch', 'Switch'), ('vacuum', 'Vacuum')], max_length=20, verbose_name='Тип устройства (Например: климатическое, освещение).')),
                ('location', models.CharField(choices=[('living_room', 'Living room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('hallway', 'Hallway'), ('bathroom', 'Bathroom'), ('outdoor', 'Outdoor')], max_length=20, verbose_name='Местоположение устройства (Например: ванная, гостинная).')),
                ('version', models.CharField(max_length=50, verbose_name='Версия устройства (Например: LG Evo Max).')),
                ('protocol', models.CharField(choices=[('wifi', 'Wifi'), ('zigbee', 'Zig Bee')], max_length=20, verbose_name='Протокол связи с устройством (Например: Wifi).')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления.')),
                ('user_uuid', models.UUIDField(db_index=True, verbose_name='UUID Пользователя Keycloak')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание.')),
            ],
            options={
                'verbose_name': 'устройство',
                'verbose_name_plural': 'Устройства',
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='unique_name_version')],
            },
        ),
    ]
