worker_processes 1;

env KEYCLOAK_REALM;
env KEYCLOAK_CLIENT_ID;
env KEYCLOAK_CLIENT_SECRET;
env KEYCLOAK_DISCOVERY;
env KEYCLOAK_REDIRECT_URI;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;

    lua_shared_dict discovery 1m;

    server {
        listen 80;
        server_name localhost;

        location / {
            access_by_lua_block {
                local openidc = require("resty.openidc")
                local _, err = openidc.authenticate({
                    discovery = os.getenv("KEYCLOAK_DISCOVERY"),
                    client_id = os.getenv("KEYCLOAK_CLIENT_ID"),
                    client_secret = os.getenv("KEYCLOAK_CLIENT_SECRET"),
                    redirect_uri = os.getenv("KEYCLOAK_REDIRECT_URI"),
                    scope = "openid profile email",
                })

                if err then
                    ngx.status = 500
                    ngx.say(err)
                    return ngx.exit(500)
                end
            }

            proxy_pass http://devices:8000;
        }
    }
}

server {
    listen 81;
    server_name _;
    
    location / {
        proxy_pass http://executor:8000;
    }
}