worker_processes 1;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s;

    lua_shared_dict discovery 1m;

    server {
        listen 80;
        server_name localhost;

        location / {
            access_by_lua_block {
                local _, err = require("resty.openidc").authenticate({
                    discovery     = "http://keycloak:8080/realms/home/.well-known/openid-configuration",
                    client_id     = "devices",
                    client_secret = "ADU1VtmY68CBUggUjlU4ENUOPgaB64uG",
                    redirect_uri  = "http://localhost/redirect_uri",
                    scope         = "openid profile email",
                })

                if err then
                    ngx.status = 500
                    ngx.say(err)
                    return ngx.exit(500)
                end
            }

            proxy_pass http://devices:8000;
        }
    }
}